apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name bookmarks-app
  labels: &labels
    app: *name
spec:
  replicas: 1
  selector:
    matchLabels:
      <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      restartPolicy: Always
      containers:
      - name: *name
        image: bookmarks/app:latest
        envFrom:
        - configMapRef:
            name: bookmarks-config
        - secretRef:
            name: bookmarks-secret
        command: ['bundle', 'exec', 'rails', 's']
