apiVersion: v1
kind: Service
metadata:
  name: bookmarks
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /up
    alb.ingress.kubernetes.io/success-codes: 200
spec:
  selector:
    app: bookmarks-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
